# -*- coding: utf-8 -*-
<TestWidget>:
    Label:
        color: [0, 0, 0, 1]
        text: '1'
        canvas.before:
            Color:
                rgb: [1, 1, 1]
            Rectangle:
                pos: self.pos
                size: self.size
    Label:
        text: '2'
        canvas.before:
            Color:
                rgb: [0.5, 0.5, 0.5]
            Rectangle:
                pos: self.pos
                size: self.size
